---
title: "DSUR 02: Plots"
author: "Andy P. Field"
date: "25/11/2019"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(discovr)
library(here)
library(Hmisc)
library(patchwork)
library(tidyverse)
library(stringr)
source("dsur_themes.R")


if(stringr::str_detect(here::here(), "Alpha")){
  volume_path <- file.path("/Volumes", "Alpha Lacertae")
} else {
  volume_path <- file.path("/Volumes", "the_repository")
}

dsr_image <- file.path(volume_path, "Documents", "Academic", "books", "discovering_statistics", "dsu_r", "dsr_02", "dsr2_docs", "dsr2_images", "dsr2_figures")
dsr_image_dev <- file.path(volume_path, "Documents", "Academic", "books", "discovering_statistics", "dsu_r", "dsr_02", "dsr2_docs", "dsr2_images", "dsr2_image_dev", "dsr2_omni_files", "dsr2_omni_dev")


cat_tib <- discovr::catterplot
exam_tib <- discovr::exam_anxiety
grammar_tib <- discovr::grammar
notebook_tib <- discovr::notebook
hiccups_tib <- discovr::hiccups
ong_tib <- ong_tidy
wish_tib <- discovr::jiminy_cricket

```

# Chapter 5

## Plot aesthetics

```{r}
d = data.frame(cbind(x = 0:25, y = 0))

shapes <- ggplot(d, aes(x = x, y = y)) +
  scale_y_continuous(name="", breaks = NULL) +
  scale_x_continuous(name="", breaks = 0:25) +
  scale_shape_identity() +
  coord_cartesian(ylim = c(-0.1, 0.1)) +
  geom_point(aes(shape = x), size=5, fill="grey") +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.ticks.y = element_blank(), axis.text.x = element_text(size = rel(1.7)), axis.ticks = element_blank())

ggsave("dsr2_fig_05_09_ggplot_shapes.pdf", shapes, width = 20, height = 4, units = "cm")
```


```{r}
l = data.frame(lines = c("blank", "solid", "dashed", "dotted", "dotdash", "longdash", "twodash"))

lines <- ggplot() +
  scale_x_continuous(limits = c(0,1), breaks = NULL, name = "") +
  scale_y_discrete(name="") +
  scale_linetype_identity() +
  geom_segment(data = l, mapping = aes(x = 0, xend = 1, y = lines, yend = lines, linetype = lines)) +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.ticks.y = element_blank(), axis.text.x = element_text(size = rel(1.7)), axis.ticks = element_blank())

ggsave("dsr2_fig_05_08_ggplot_lines.pdf", lines, width = 10, height = 6, units = "cm")
```


## Facet_wrap

```{r}
ong_plot <- ong_tib %>% 
  dplyr::filter(is.na(sex) == FALSE) %>% 
  ggplot(., aes(narcissism, rating)) +
  geom_point(colour = ong, alpha = 0.7, position = position_jitter()) +
  coord_cartesian(xlim = c(0, 60)) +
  scale_x_continuous(breaks = seq(0, 60, 10)) +
  labs(x = "Narcissism (NPQC Total)", y = "Profile rating (1-5)") +
  theme_light() +
  theme(strip.background = element_rect(colour = blu_dk, fill = blu))

ong_fg <- ong_plot + facet_grid(rating_type ~ sex)
ong_fg

ggplot2::ggsave(filename = "dsr2_fig_05_10_facet_grid.pdf", plot = ong_fw, width = 10, height = 15, unit = "cm")

ong_fw_row <- ong_plot + facet_wrap( ~ rating_type, nrow = 1)
ong_fw_row

ggplot2::ggsave(filename = "dsr2_fig_05_10_facet_wrap_row.pdf", plot = ong_fw_row, width = 20, height = 5, unit = "cm")

ong_fw_col <- ong_plot + facet_wrap( ~ rating_type, ncol = 1)
ong_fw_col

ggplot2::ggsave(filename = "dsr2_fig_05_10_facet_wrap_col.pdf", plot = ong_fw_col, width = 10, height = 15, unit = "cm")

```

## Themes

```{r}
cool_plot <- ong_tidy %>% 
  dplyr::select(rating_type, narcissism, rating) %>% 
  dplyr::filter(rating_type == "Cool") %>% 
  na.omit() %>% 
  ggplot(., aes(narcissism, rating)) +
  geom_point(alpha = 0.7, position = position_jitter()) +
  geom_smooth(method = "lm") + 
  coord_cartesian(xlim = c(10, 55)) +
  scale_x_continuous(breaks = seq(10, 50, 10)) +
  labs(x = "Narcissism (NPQC Total)", y = "Coolness rating (1-5)")

cool_plot %>% ggplot2::ggsave(filename = "dsr2_fig_05_11_theme_grey.pdf", width = 10, height = 7, unit = "cm")

cool_bw <- cool_plot + 
  theme_bw()
cool_bw %>% ggplot2::ggsave(filename = "dsr2_fig_05_11_theme_bw.pdf", width = 10, height = 7, unit = "cm")

cool_light <- cool_plot + 
  theme_light()
cool_light %>% ggplot2::ggsave(filename = "dsr2_fig_05_11_theme_light.pdf", width = 10, height = 7, unit = "cm")

cool_dark <- cool_plot + 
  theme_dark()
cool_dark %>% ggplot2::ggsave(filename = "dsr2_fig_05_11_theme_dark.pdf", width = 10, height = 7, unit = "cm")

cool_minimal <- cool_plot + 
  theme_minimal()
cool_minimal %>% ggplot2::ggsave(filename = "dsr2_fig_05_11_theme_minimal.pdf", width = 10, height = 7, unit = "cm")

cool_classic <- cool_plot + 
  theme_classic()
cool_classic %>% ggplot2::ggsave(filename = "dsr2_fig_05_11_theme_classic.pdf", width = 10, height = 7, unit = "cm")
```

Test out some theme adjustments:

```{r}

cool_sex <- ong_tidy %>% 
  dplyr::select(rating_type, narcissism, rating, sex) %>% 
  dplyr::filter(rating_type == "Cool") %>% 
  na.omit() %>% 
  ggplot(., aes(narcissism, rating, colour = sex)) +
  geom_point(alpha = 0.7, position = position_jitter()) +
  geom_smooth(method = "lm") + 
  coord_cartesian(xlim = c(10, 55)) +
  scale_x_continuous(breaks = seq(10, 50, 10)) +
  labs(x = "Narcissism (NPQC Total)", y = "Coolness rating (1-5)", title = "Plot of Narcissism against coolness ratings of Facebook profile pictures", subtitle = "Ong et al., 2011", caption = "Figure 1")

cool_sex +
  theme(axis.title = element_text(family = "Courier", colour = "#b50000", face = "italic", hjust = 0))

cool_sex +
  theme(axis.text.x = element_text(angle = 45))

cool_sex +
  theme(axis.title = element_text(size = rel(1.5)))

cool_sex +
  theme(legend.text = element_text(face = "bold"))

cool_sex +
  theme(legend.title = element_text(size = rel(2)))

cool_sex +
  theme(plot.title = element_text(family = "Times"))

cool_sex +
  theme(plot.subtitle = element_text(family = "Times", face = "italic"))

cool_sex +
  theme(plot.caption = element_text(hjust = 0))

cool_sex +
  facet_wrap(~sex) +
  theme(strip.text = element_text(colour = "#b50000", face = "bold"))

cool_sex +
  theme(axis.line = element_line(colour = "#b50000"))

cool_sex +
  theme(axis.ticks = element_line(colour = "#b50000"))

cool_sex +
  theme(panel.grid = element_line(linetype = 2, colour = "#aa8f00"))

cool_sex +
  theme(legend.background = element_rect(colour = "#634806", fill = "#aa8f00"))

cool_sex +
  theme(legend.key = element_rect(fill = "#aa8f00"))

cool_sex +
  theme(panel.background = element_rect(fill = "#aa8f00"))

cool_sex +
  theme(panel.border = element_rect(colour = "#634806", fill = NA))

cool_sex +
  theme(plot.background = element_rect(fill = "#545454"))

cool_sex +
  facet_wrap(~sex) +
  theme(strip.background = element_rect(colour = "#634806", fill = "#aa8f00"))

cool_sex +
  theme(legend.position = "none")

cool_sex +
  theme(legend.position = c(0.9, 0.2))



cool_abomination <- cool_sex +
  theme(plot.title = element_text(size = rel(0.8)), axis.title = element_text(family = "Courier"), axis.text.x = element_text(angle = 45), legend.background = element_rect(colour = "#634806", fill = "#aa8f00"), axis.line = element_line(colour = "#b50000"), panel.background = element_rect(fill = "#aa8f00"), plot.caption = element_text(hjust = 0))

cool_sex %>% ggplot2::ggsave(filename = "dsr2_fig_05_12_default.pdf", width = 15, height = 10, unit = "cm")

cool_abomination %>% ggplot2::ggsave(filename = "dsr2_fig_05_12_abomination.pdf", width = 15, height = 10, unit = "cm")


```

## Histograms

```{r}

wish_hist <- ggplot2::ggplot(wish_tib, aes(success)) +
  geom_histogram(binwidth = 5)

wish_hist %>% ggplot2::ggsave(filename = "dsr2_fig_05_14_base.pdf", width = 15, height = 10, unit = "cm")

wish_hist <- ggplot2::ggplot(wish_tib, aes(success)) +
  geom_histogram(binwidth = 5, fill = "#56B4E9")

wish_hist %>% ggplot2::ggsave(filename = "dsr2_fig_05_14_fill.pdf", width = 15, height = 10, unit = "cm")

wish_hist <- ggplot2::ggplot(wish_tib, aes(success)) +
  geom_histogram(binwidth = 5, fill = "#56B4E9", colour = "#336c8b")

wish_hist %>% ggplot2::ggsave(filename = "dsr2_fig_05_14_colour.pdf", width = 15, height = 10, unit = "cm")

wish_hist <-ggplot2::ggplot(wish_tib, aes(success)) +
  geom_histogram(binwidth = 5, fill = "#56B4E9", colour = "#336c8b", alpha = 0.2)

wish_hist %>% ggplot2::ggsave(filename = "dsr2_fig_05_14_alpha.pdf", width = 15, height = 10, unit = "cm")

wish_hist <- wish_hist +
  labs(y = "Frequency", x = "Success scores (0-100)", title = "Histogram of success scores")

wish_hist %>% ggplot2::ggsave(filename = "dsr2_fig_05_14_labs.pdf", width = 15, height = 10, unit = "cm")

wish_hist <- wish_hist +
  theme_minimal()

wish_hist %>% ggplot2::ggsave(filename = "dsr2_fig_05_14_theme.pdf", width = 15, height = 10, unit = "cm")

wish_hist <- wish_hist +
  facet_grid(strategy~time)

wish_hist %>% ggplot2::ggsave(filename = "dsr2_fig_05_15_facet_grid.pdf", width = 15, height = 10, unit = "cm")
```


## Frequency Polygons

```{r}
wish_poly <- ggplot2::ggplot(wish_tib, aes(success)) +
 geom_freqpoly(binwidth = 5, colour = "#336c8b") +
 labs(y = "Frequency", x = "Success scores (0-100)", title = "Histogram of success scores") +
 facet_grid(strategy~time) +
 theme_minimal()

wish_poly %>% ggplot2::ggsave(filename = "dsr2_fig_05_16_freq_poly.pdf", width = 15, height = 10, unit = "cm")


wish_poly_dashed <- ggplot2::ggplot(wish_tib, aes(success)) +
 geom_freqpoly(binwidth = 5, colour = "#336c8b", linetype = 2) +
 labs(y = "Frequency", x = "Success scores (0-100)", title = "Histogram of success scores") +
 facet_grid(strategy~time) +
 theme_minimal()

wish_poly_dashed %>% ggplot2::ggsave(filename = "dsr2_fig_05_17_freq_poly_dash.pdf", width = 15, height = 10, unit = "cm")

wish_poly_fat <- ggplot2::ggplot(wish_tib, aes(success)) +
 geom_freqpoly(binwidth = 5, colour = "#336c8b", size = 2) +
 labs(y = "Frequency", x = "Success scores (0-100)", title = "Histogram of success scores") +
 facet_grid(strategy~time) +
 theme_minimal()

wish_poly_fat %>% ggplot2::ggsave(filename = "dsr2_fig_05_17_freq_poly_size.pdf", width = 15, height = 10, unit = "cm")



```

## Boxplots

```{r}
wish_plot <- ggplot2::ggplot(wish_tib, aes(time, success)) +
  geom_boxplot(fill = blu, alpha = 0.5) +
  scale_y_continuous(breaks = seq(0, 100, 10)) +
  labs(x = "Time", y = "Success (out of 100)") +
  theme_minimal()

wish_plot %>% ggplot2::ggsave(filename = file.path(dsr_image_dev, "dsr2_fig_05_18_boxplot.pdf"), width = 15, height = 10, unit = "cm")

#basic boxplot

wish_basic <- ggplot2::ggplot(wish_tib, aes(time, success)) +
  geom_boxplot()

wish_basic %>% ggplot2::ggsave(filename = file.path(dsr_image_dev, "dsr2_fig_05_19_boxplot_basic.pdf"), width = 15, height = 10, unit = "cm")

wish_final <- ggplot2::ggplot(wish_tib, aes(time, success)) +
  geom_boxplot(fill = "#5c97bf", alpha = 0.7) +
  scale_y_continuous(breaks = seq(0, 100, 10)) +
  labs(x = "Time", y = "Success (out of 100)") +
  theme_minimal()

wish_final %>% ggplot2::ggsave(filename = file.path(dsr_image_dev, "dsr2_fig_05_19_boxplot_final.pdf"), width = 15, height = 10, unit = "cm")


wish_facet <- ggplot2::ggplot(wish_tib, aes(time, success)) +
  geom_boxplot(fill = "#5c97bf", alpha = 0.7) +
  scale_y_continuous(breaks = seq(0, 100, 10)) +
  labs(x = "Time", y = "Success (out of 100)") +
  facet_wrap(~ strategy) +
  theme_minimal()


wish_fill <- ggplot2::ggplot(wish_tib, aes(time, success, fill = strategy)) +
  geom_boxplot(alpha = 0.7) +
  scale_y_continuous(breaks = seq(0, 100, 10)) +
  labs(x = "Time", y = "Success (out of 100)", fill = "Success strategy") +
  theme_minimal()

wish_strategy <- patchwork::wrap_plots(wish_facet, wish_fill, ncol = 1) # does the same as wish_facet/wish_fill but I want to be explicit about using patchwork

wish_strategy %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_20_boxplot_strategy.pdf"), width = 15, height = 15, unit = "cm")


wish_fill_manual <- ggplot2::ggplot(wish_tib, aes(time, success, fill = strategy)) +
  geom_boxplot(alpha = 0.7) +
  scale_y_continuous(breaks = seq(0, 100, 10)) +
  labs(x = "Time", y = "Success (out of 100)", fill = "Success strategy") +
  scale_fill_manual(values = c("#16a085", "#d47500")) +
  theme_minimal()

wish_fill_manual %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_21_boxplot_fill_manual.pdf"), width = 15, height = 10, unit = "cm")
```

## Plotting means

```{r, means_not_used}
wish_mean <- ggplot2::ggplot(wish_tib, aes(time, success)) +
  stat_summary(fun.y = "mean", geom = "point", size = 4) +
  scale_y_continuous(breaks = seq(0, 100, 10)) +
  labs(x = "Time", y = "Success (out of 100)") +
  theme_minimal()
  
wish_mean_adj <- ggplot2::ggplot(wish_tib, aes(time, success)) +
  stat_summary(fun.y = "mean", geom = "point", size = 4) +
  coord_cartesian(ylim = c(0, 70)) +
  scale_y_continuous(breaks = seq(0, 70, 10)) +
  labs(x = "Time", y = "Success (out of 100)") +
  theme_minimal()


 wish_mean_ci <- ggplot2::ggplot(wish_tib, aes(time, success)) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange", size = 0.5) +
  coord_cartesian(ylim = c(0, 70)) +
  scale_y_continuous(breaks = seq(0, 70, 10)) +
  labs(x = "Time", y = "Success (out of 100)") +
  theme_minimal()


wish_means <- patchwork::wrap_plots(wish_mean, wish_mean_adj, wish_mean_ci,  ncol = 1) # does the same as wish_facet/wish_fill but I want to be explicit about using patchwork

wish_means %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_22_means.pdf"), width = 15, height = 24, unit = "cm")

 wish_mean_ci_group <- ggplot2::ggplot(wish_tib, aes(time, success)) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange") +
  coord_cartesian(ylim = c(0, 70)) +
  scale_y_continuous(breaks = seq(0, 70, 10)) +
  labs(x = "Time", y = "Success (out of 100)") +
  facet_wrap(~strategy) +
  theme_minimal()
 
 wish_mean_ci_group_colour <- ggplot2::ggplot(wish_tib, aes(time, success, colour = strategy)) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange") +
  coord_cartesian(ylim = c(0, 70)) +
  scale_y_continuous(breaks = seq(0, 70, 10)) +
  labs(x = "Time", y = "Success (out of 100)", colour = "Success strategy") +
  theme_minimal() 

 wish_mean_ci_group_colour_adj <- ggplot2::ggplot(wish_tib, aes(time, success, colour = strategy)) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange", position = position_dodge(width = 0.5)) +
  coord_cartesian(ylim = c(0, 70)) +
  scale_y_continuous(breaks = seq(0, 70, 10)) +
  labs(x = "Time", y = "Success (out of 100)", colour = "Success strategy") +
  theme_minimal() 
 
 wish_group <- patchwork::wrap_plots(wish_mean_ci_group, wish_mean_ci_group_colour, wish_mean_ci_group_colour_adj,  ncol = 1) # does the same as wish_facet/wish_fill but I want to be explicit about using patchwork

wish_group %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_23_means_group.pdf"), width = 15, height = 24, unit = "cm")

```

```{r}

note_mean <- ggplot2::ggplot(notebook_tib, aes(film, arousal))

note_mean_raw <- note_mean +
  stat_summary(fun.y = "mean", geom = "point", size = 3) +
  labs(x = "Type of film", y = "Arousal (out of 100)") +
  theme_minimal()
  
note_mean_adj <- note_mean +
  stat_summary(fun.y = "mean", geom = "point", size = 3)+
  coord_cartesian(ylim = c(0, 50)) +
  scale_y_continuous(breaks = seq(0, 50, 5)) +
  labs(x = "Type of film", y = "Arousal (out of 100)") +
  theme_minimal()


note_mean_ci <- note_mean +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange") +
  coord_cartesian(ylim = c(0, 50)) +
  scale_y_continuous(breaks = seq(0, 50, 5)) +
  labs(x = "Type of film", y = "Arousal (out of 100)") +
  theme_minimal()


note_means <- patchwork::wrap_plots(note_mean_raw, note_mean_adj, note_mean_ci,  ncol = 1)

note_means %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_22_means.pdf"), width = 15, height = 24, unit = "cm")


 note_mean_ci_group <- note_mean +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange") +
  coord_cartesian(ylim = c(0, 50)) +
  scale_y_continuous(breaks = seq(0, 50, 5)) +
  labs(x = "Type of film", y = "Arousal (out of 100)") +
  facet_wrap(~sex) +
  theme_minimal()
 
 note_mean <- ggplot2::ggplot(notebook_tib, aes(film, arousal, colour = sex))

 
 note_mean_ci_group_colour <- note_mean +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange") +
  coord_cartesian(ylim = c(0, 50)) +
  scale_y_continuous(breaks = seq(0, 50, 5)) +
  labs(x = "Type of film", y = "Arousal (out of 100)", colour = "Biological sex") +
  theme_minimal() 

 note_mean_ci_group_colour_adj <- note_mean +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange", position = position_dodge(width = 0.5)) +
  coord_cartesian(ylim = c(0, 50)) +
  scale_y_continuous(breaks = seq(0, 50, 5)) +
  labs(x = "Type of film", y = "Arousal (out of 100)", colour = "Biological sex") +
  theme_minimal() 
 
note_group <- patchwork::wrap_plots(note_mean_ci_group, note_mean_ci_group_colour, note_mean_ci_group_colour_adj,  ncol = 1)

note_group %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_23_means_group.pdf"), width = 15, height = 24, unit = "cm")

```

## Violin plots

```{r}
note_viol <- ggplot2::ggplot(notebook_tib, aes(sex, arousal, fill = str_wrap(film, width = 15)))

note_viol_box_raw <- note_viol +
  geom_violin() +
  geom_boxplot() +
  labs(x = "Biological sex", y = "Arousal", fill = "Film watched") +
  coord_cartesian(ylim = c(0, 50)) +
  scale_y_continuous(breaks = seq(0, 50, 5)) +
  theme_minimal() +
  theme(legend.position = "none")

note_viol_box_adj <- note_viol +
  geom_violin(alpha = 0.7) +
  geom_boxplot(alpha = 0, width = 0.2, position = position_dodge(width = 0.9)) +
  labs(x = "Biological sex", y = "Arousal", fill = "Film watched") +
  coord_cartesian(ylim = c(0, 50)) +
  scale_y_continuous(breaks = seq(0, 50, 5)) +
  theme_minimal()


note_viol_dot_raw <- note_viol +
  geom_violin() +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange", position = position_dodge(width = 0.5)) +
  labs(x = "Biological sex", y = "Arousal", fill = "Film watched") +
  coord_cartesian(ylim = c(0, 50)) +
  scale_y_continuous(breaks = seq(0, 50, 5)) +
  theme_minimal() +
  theme(legend.position = "none")

note_viol_dot_adj <- note_viol +
  geom_violin(alpha = 0.7) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange", position = position_dodge(width = 0.9)) +
  labs(x = "Biological sex", y = "Arousal", fill = "Film watched") +
  coord_cartesian(ylim = c(0, 50)) +
  scale_y_continuous(breaks = seq(0, 50, 5)) +
  theme_minimal() +
  guides(fill = guide_legend(nrow = 2))

note_violins <- patchwork::wrap_plots(note_viol_dot_raw, note_viol_dot_adj, note_viol_box_raw, note_viol_box_adj,  ncol = 2)

note_violins %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_24_violins.pdf"), width = 20, height = 15, unit = "cm")


note_viol_dot_raw_wrong <- note_viol +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange", position = position_dodge(width = 0.9)) +
  geom_violin() +
  labs(x = "Biological sex", y = "Arousal", fill = "Film watched") +
  theme_minimal() +
  theme(legend.position = "none")

note_viol_dot_raw_right <- note_viol +
  geom_violin() +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange", position = position_dodge(width = 0.9)) +
  labs(x = "Biological sex", y = "Arousal", fill = "Film watched") +
  theme_minimal()

order_matters_violins <- patchwork::wrap_plots(note_viol_dot_raw_wrong, note_viol_dot_raw_right,  ncol = 2)

order_matters_violins %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_25_order_matters.pdf"), width = 20, height = 7, unit = "cm")

```

## Repeated measures

```{r}
hiccup_plot <- ggplot2::ggplot(hiccups_tib, aes(intervention, hiccups)) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange") +
  labs(x = "Intervention", y = "Number of hiccups") +
  coord_cartesian(ylim = c(0, 20)) +
  scale_y_continuous(breaks = seq(0, 20, 5)) +
  theme_minimal()

hiccup_plot %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_27_hiccup_plot.pdf"), width = 15, height = 10, unit = "cm")
```

## Mixed designs

```{r}
grammar_plot <- ggplot2::ggplot(grammar_tib, aes(time, grammar, colour = media_use)) 
grammar_plot_no_line <- grammar_plot +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange", position = position_dodge(width = 0.05)) +
  labs(x = "Time", y = "Grammar score (%)", colour = "Media use") +
  coord_cartesian(ylim = c(0, 75)) +
  scale_y_continuous(breaks = seq(0, 75, 5)) +
  theme_minimal() +
  theme(legend.position = "none")

grammar_plot_line <- grammar_plot +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange", position = position_dodge(width = 0.05)) +
  stat_summary(fun.y = "mean", geom = "line", position = position_dodge(width = 0.05), aes(group = media_use)) +
  labs(x = "Time", y = "Grammar score (%)", colour = "Media use") +
  coord_cartesian(ylim = c(0, 75)) +
  scale_y_continuous(breaks = seq(0, 75, 5)) +
  theme_minimal()

adding_lines <- patchwork::wrap_plots(grammar_plot_no_line, grammar_plot_line,  ncol = 2)

adding_lines %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_29_grammar_plot.pdf"), width = 20, height = 10, unit = "cm")
```

## Scatterplots

```{r}
exam_plot <- ggplot(exam_tib, aes(anxiety, exam_grade))

exam_plot <- exam_plot +
  geom_point() +
  labs(x = "Exam anxiety", y = "Exam performance (%)") +
  coord_cartesian(ylim = c(0, 130)) +
  scale_y_continuous(breaks = seq(0, 130, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10)) +
  theme_minimal()

exam_plot %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_36_scatterplot.pdf"), width = 15, height = 10, unit = "cm")

exam_plot <- ggplot(exam_tib, aes(anxiety, exam_grade))
exam_smooth <- exam_plot +
  geom_point() +
  geom_smooth() +
  labs(x = "Exam anxiety", y = "Exam performance (%)") +
  coord_cartesian(ylim = c(0, 130)) +
  scale_y_continuous(breaks = seq(0, 130, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10)) +
  theme_minimal()

exam_lm <- exam_plot +
  geom_point() +
  geom_smooth(method = "lm", colour = "#ef4836", fill = "#ef4836") +
  labs(x = "Exam anxiety", y = "Exam performance (%)") +
  coord_cartesian(ylim = c(0, 130)) +
  scale_y_continuous(breaks = seq(0, 130, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10)) +
  theme_minimal()

smoothers <- patchwork::wrap_plots(exam_smooth, exam_lm,  ncol = 2)


smoothers %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_37_smoothers.pdf"), width = 20, height = 10, unit = "cm")

```


```{r catterplot}

catterplot <- ggplot(cat_tib, aes(dinner_time, meow))
catterplot <- catterplot +
  geom_point(colour = ong_dk, size = 2) +
  scale_y_continuous(breaks = seq(0, 16, 2)) +
  scale_x_continuous(breaks = seq(0, 24, 2)) +
  labs(x = "Time since dinner (hours)", y = "Purr volume") +
  theme_minimal()

catterplot %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_38_catterplot.pdf"), width = 10, height = 7, unit = "cm")

```

```{r}
exam_sex <- ggplot(exam_tib, aes(anxiety, exam_grade, colour = sex))  +
  geom_point() +
  geom_smooth(method = "lm", aes(fill = sex), alpha = 0.1) +
  labs(x = "Exam anxiety", y = "Exam performance (%)", colour = "Biological sex", fill = "Biological sex") +
  coord_cartesian(ylim = c(0, 130)) +
  scale_y_continuous(breaks = seq(0, 130, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10)) +
  theme_minimal()

exam_sex %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_39_group_scatterplot.pdf"), width = 15, height = 10, unit = "cm")

```

```{r}
ong_mtx <- GGally::ggpairs(ong_tib, columns = c("rating", "extraversion", "narcissism"))

ong_mtx %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_40_matrix_scatterplot.pdf"), width = 20, height = 15, unit = "cm")

ong_mtx_2 <- GGally::ggpairs(ong_tib, columns = c("rating", "extraversion", "narcissism"), mapping = aes(color = rating_type, alpha = 0.1)) +
  theme_minimal()

ong_mtx_2 %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_05_41_matrix_colour_scatterplot.pdf"), width = 25, height = 20, unit = "cm")

```

