---
title: "Robust sim_slopes"
author: "Andy P. Field"
date: "15/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
```

## Load data and centre variables

```{r}
vids_tib <- readr::read_csv("http://milton-the-cat.rocks/home/data/r_data/video_games.csv") %>% 
  dplyr::mutate(
    caunts_cent = caunts - mean(caunts, na.rm = TRUE),
    vid_game_cent = vid_game - mean(vid_game, na.rm = TRUE)
  )
```

## Fitting the main model

```{r}
aggress_lm <- lm(aggress ~ caunts_cent + vid_game_cent + caunts_cent:vid_game_cent, data = vids_tib)
```

## Simple slopes non-robust SEs

```{r}
interactions::sim_slopes(
  aggress_lm,
  pred = vid_game_cent,
  modx = caunts_cent,
  confint = TRUE
  )
```

## Simple slopes robust SEs

```{r}
interactions::sim_slopes(
  aggress_lm,
  pred = vid_game_cent,
  modx = caunts_cent,
  robust = TRUE,
  confint = TRUE
  )
```

## Simple slopes HC3 specified

```{r}
interactions::sim_slopes(
  aggress_lm,
  pred = vid_game_cent,
  modx = caunts_cent,
  robust = "HC3",
  confint = TRUE
  )
```

## Simple slopes HC4 specified

```{r}
interactions::sim_slopes(
  aggress_lm,
  pred = vid_game_cent,
  modx = caunts_cent,
  robust = "HC3",
  confint = TRUE
  )
```