---
title: "Bronstein data sim"
author: "Andy P. Field"
date: "21/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(magrittr)

here::here("/data-raw/data_functions.R") %>% source()

bron_tib <- haven::read_sav("bronstein_et_al.sav") %>%
  haven::zap_formats() %>%
  haven::zap_label() %>%
  haven::zap_widths() %>% 
  dplyr::rename(
    id = ResponseID,
    aot_z = ZAOT_Total,
    dog_z = ZDOG_Total,
    rf_z = ZRF_Total,
    belief_fake_z = ZBelief_Fake,
    belief_real_z =ZBelief_Real,
    pdi_z = ZPDI_Total,
    crt_z = ZCRT_Number_Correct
    ) %>%
  dplyr::rename_all(tolower) %>%
  dplyr::mutate(
    sex = factor(sex, levels = 1:2, labels = c("Male", "Female")),
  ) %>% 
  dplyr::select(id, age, sex, aot_z, dog_z, rf_z, belief_fake_z, belief_real_z, pdi_z, crt_z)

bron_mini_tib <- bron_tib %>% 
  dplyr::select(id, aot_z, belief_fake_z, pdi_z, crt_z) %>% 
  dplyr::rename(
    thinkz_open = aot_z,
    thinkz_anal = crt_z,
    delusionz = pdi_z,
    fake_newz = belief_fake_z
  )
```

```{r, eval = FALSE}
bron_mini_tib %>% 
  readr::write_csv(., path = here::here("data-raw/bronstein_2019.csv"))
```

# Replicate their mediation model:

```{r}

bron_mini_tib %>% 
  dplyr::select(-id) %>% 
  correlation::correlation(method = "spearman")

bron_mod <- 'fake_newz ~ c*delusionz + b1*thinkz_open + b2*thinkz_anal
                   thinkz_open ~ a1*delusionz
                   thinkz_anal ~ a2*delusionz

                   indirect_open := a1*b1
                   indirect_anal := a2*b2
                   total_effect := c + (a1*b1) + (a2*b2)
                   thinkz_open ~~ thinkz_anal
                   '
bron_fit <- lavaan::sem(bron_mod, data = bron_mini_tib, se = "bootstrap")
broom::tidy(bron_fit, conf.int = TRUE) %>%
  dplyr::mutate_if(
    vars(is.numeric(.)),
    list(~round(., 3))
  )


broom::glance(bron_fit)
```

# Introduce missing data at random

```{r eval = FALSE}
patterns <- rbind(
  c(1, 1, 1, 0),
  c(1, 1, 0, 1),
  c(1, 0, 1, 1),
  c(0, 1, 1, 0),
  c(1, 0, 1, 0),
  c(0, 1, 1, 0),
  c(1, 0, 0, 1)
)

set.seed(666)
bron_amp <- bron_mini_tib %>% 
  dplyr::select(thinkz_open, fake_newz, delusionz, thinkz_anal) %>% 
  mice::ampute(prop = 0.2, mech = "MCAR", patterns = patterns, freq = c(0.3, 0.2, 0.2, 0.13, 0.05, 0.08, 0.04))

bron_missing_tib <- bron_amp$amp %>% 
  dplyr::mutate(
    id = bron_mini_tib$id
  ) %>% 
  dplyr::select(id, thinkz_open:thinkz_anal)
```


```{r}
bron_missing_tib %>% 
  readr::write_csv(., path = here::here("data-raw/bronstein_miss_2019.csv"))
```


```{r}
bron_missing_tib %>%
  dplyr::select(-id) %>% 
  mice::md.pattern(., rotate.names = TRUE)
  
```

# Multiple imputation of model

```{r}

bron_imps <- bron_missing_tib %>% 
  dplyr::select(-id) %>% 
  mice::mice(method = "pmm", m = 20)

bron_imp_lst <- NULL
for(i in 1:20){
   bron_imp_lst[[i]] <- mice::complete(bron_imps, action = i, include = FALSE)
}

complete(bron_imps, 1)

test_mod <- 'fake_newz ~ a*delusionz + b*thinkz_open + c*delusionz:thinkz_open'
test_fit <- lavaan::sem(test_mod, data = bron_tib, meanstructure=TRUE)
broom::tidy(test_fit, conf.int = TRUE) %>%
  dplyr::mutate_if(
    vars(is.numeric(.)),
    list(~round(., 3))
  )

lm(fake_newz ~ delusionz*thinkz_open, data = bron_tib) %>% summary()

test_mi_fit <- semTools::sem.mi(test_mod, data = bron_imp_lst)
summary(test_mi_fit)


bron_mi_fit <- semTools::runMI(bron_mod, data = bron_imp_lst, fun = "sem")
(bron_mi_fit)



#*********


fit <- with(bron_imps, lm(fake_newz ~ delusionz*thinkz_open))
fit

pool.fit <- mice::pool(fit)
summary(pool.fit)
  
```

