---
title: "DSUR 02 Chapter 10: Plots"
author: "Andy P. Field"
date: "25/11/2019"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(discovr)
library(here)
library(patchwork)
library(tidyverse)
source("../dsur_themes.R")


if(stringr::str_detect(here::here(), "Alpha")){
  volume_path <- file.path("/Volumes", "Alpha Lacertae")
} else {
  volume_path <- file.path("/Volumes", "the_repository")
}

dsr_image <- file.path(volume_path, "Documents", "Academic", "books", "discovering_statistics", "dsu_r", "dsr_02", "dsr2_docs", "dsr2_images", "dsr2_figures", "dsr2_ch_10_figures")
dsr_image_dev <- file.path(volume_path, "Documents", "Academic", "books", "discovering_statistics", "dsu_r", "dsr_02", "dsr2_docs", "dsr2_images", "dsr2_image_dev", "dsr2_omni_files", "dsr2_omni_dev")



vids_tib <- discovr::video_games
infidelity_tib <- discovr::lambert_2012
newz_md_tib <- discovr::bronstein_miss_2019

```

## Categorical moderator

```{r}

vidGames<-read.spss(file.path(spssDataDirectory, "Chapter 11 (Mediation)", "Video Games.sav"), to.data.frame = T)
names(vids_tib)

vids_tib <- vids_tib %>% 
  dplyr::mutate(
    callous_cat = ifelse(caunts > 26, "Callous", "Not Callous")
  )


cut_cat_plot <- ggplot(vids_tib, aes(vid_game, aggress, colour = callous_cat)) +
  geom_point(size = 2, alpha = 0.7) +
  geom_smooth(method = "lm", aes(fill = callous_cat), alpha = 0.1) +
  labs(x = "Hours playing video games", y = "Aggression", colour = "Callous traits", fill = "Callous traits") +
  scale_colour_manual(values = c(blu, ong)) +
  scale_fill_manual(values = c(blu, ong)) +
  theme_minimal()

cut_cat_plot %>%
  ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_10_04_categorical_moderator.pdf"), width = 15, height = 10, unit = "cm")

```

## Moderation

```{r}

vids_tib <- vids_tib %>% 
  dplyr::mutate(
    caunts_cent = caunts - mean(caunts, na.rm = TRUE),
    vid_game_cent = vid_game - mean(vid_game, na.rm = TRUE)
  )

aggress_lm <- lm(aggress ~ caunts_cent*vid_game_cent, data = vids_tib)

agress_jn <- interactions::sim_slopes(
  aggress_lm,
  pred = vid_game_cent,
  modx = caunts_cent,
  jnplot = TRUE,
  robust = TRUE
  )

agress_jn$jnplot %>% 
  ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_10_07_johnson-neyman_interval.pdf"), width = 15, height = 10, unit = "cm")


agress_simslop <- interactions::interact_plot(
  aggress_lm,
  pred = vid_game_cent,
  modx = caunts_cent,
  interval = TRUE,
  x.label = "Time playing video games per week (hours)",
  y.label = "Predicted agression",
  legend.main = "Callous unemotional traits"
  )

agress_simslop %>% 
  ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_10_08_simple_slopes.pdf"), width = 15, height = 10, unit = "cm")

```

## Missing data

```{r}
set.seed(616)
newz_md_tib %>% 
  dplyr::sample_n(., 10)
```




```{r}
pdf(file=file.path(dsr_image_dev, "dsr2_fig_10_15_md_pattern.pdf"), width = 10, height = 7)
newz_md_tib %>%
  dplyr::select(-id) %>% 
  mice::md.pattern(., rotate.names = TRUE)
dev.off()
```








