---
title: "DSUR 02 Chapter 9: Plots"
author: "Andy P. Field"
date: "25/11/2019"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(discovr)
library(here)
library(Hmisc)
library(patchwork)
library(qqplotr)
library(tidyverse)
library(stringr)
source("dsur_themes.R")


if(stringr::str_detect(here::here(), "Alpha")){
  volume_path <- file.path("/Volumes", "Alpha Lacertae")
} else {
  volume_path <- file.path("/Volumes", "the_repository")
}

dsr_image <- file.path(volume_path, "Documents", "Academic", "books", "discovering_statistics", "dsu_r", "dsr_02", "dsr2_docs", "dsr2_images", "dsr2_figures", "dsr2_ch_09_figures")
dsr_image_dev <- file.path(volume_path, "Documents", "Academic", "books", "discovering_statistics", "dsu_r", "dsr_02", "dsr2_docs", "dsr2_images", "dsr2_image_dev", "dsr2_omni_files", "dsr2_omni_dev")



cloak_tib <- discovr::invisibility_cloak
```


```{r}
cloak_plot <- ggplot2::ggplot(cloak_tib, aes(cloak, mischief)) +
  geom_violin() +
  stat_summary(fun.data = "mean_cl_normal") +
  labs(x = "Cloak group", y = "Acts of mischief") +
  theme_minimal()


cloak_plot %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_09_04_invisible_violin.pdf"), width = 15, height = 10, unit = "cm")

```

```{r}
cloak_messy_tib <- cloak_rm_tib %>% 
  tidyr::spread(value = mischief, key = cloak) %>% 
  dplyr::mutate(
    diff = Cloak - `No cloak`
  )

cloak_messy_tib %>% print(n = 12)
```

```{r}
diff_qq <- cloak_rm_tib %>% 
  tidyr::spread(value = mischief, key = cloak) %>% 
  dplyr::mutate(
    diff = Cloak - `No cloak`
  ) %>%
  ggplot2::ggplot(., aes(sample = diff)) 

diff_qq <- diff_qq +
  qqplotr::stat_qq_band(fill = "#5c97bf", alpha = 0.3) +
  qqplotr::stat_qq_line(colour = "#5c97bf") +
  qqplotr::stat_qq_point() +
  labs(x = "Theoretical quantiles", y = "Sample quantiles") +
  theme_minimal()

diff_qq %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_09_07_invisible_qq.pdf"), width = 15, height = 10, unit = "cm")

```





