---
title: "DSUR 02 Chapter 7: Plots"
author: "Andy P. Field"
date: "25/11/2019"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(discovr)
library(here)
library(Hmisc)
library(patchwork)
library(tidyverse)
library(stringr)
source("../r_docs/dsur_themes.R")


if(stringr::str_detect(here::here(), "Alpha")){
  volume_path <- file.path("/Volumes", "Alpha Lacertae")
} else {
  volume_path <- file.path("/Volumes", "the_repository")
}

dsr_image <- file.path(volume_path, "Documents", "Academic", "books", "discovering_statistics", "dsu_r", "dsr_02", "dsr2_docs", "dsr2_images", "dsr2_figures")
dsr_image_dev <- file.path(volume_path, "Documents", "Academic", "books", "discovering_statistics", "dsu_r", "dsr_02", "dsr2_docs", "dsr2_images", "dsr2_image_dev", "dsr2_omni_files", "dsr2_omni_dev")



exam_tib <- discovr::exam_anxiety
```

# Chapter 7

```{r}
exam_mtx <- GGally::ggscatmat(exam_tib, columns = c("exam_grade", "revise", "anxiety")) +
  theme_minimal()

exam_mtx %>% ggplot2::ggsave(filename = file.path(dsr_image, "dsr2_fig_07_07_matrix_scatterplot.pdf"), width = 15, height = 15, unit = "cm")

```

## Boot function

```{r, eval = FALSE}

# Create data and save it

bs <- dplyr::sample_n(exam_tib, 7) %>% 
  dplyr::mutate(
    anxiety = round(anxiety),
    row = row_number()
  ) %>% 
  dplyr::select(row, revise:anxiety)

bs_tib <- bs %>% 
  dplyr::mutate(
      sample = "Data"
    ) %>% 
  dplyr::select(sample, row:anxiety)

for(i in 1:5){
  bsample <- dplyr::sample_n(bs, 7, replace = TRUE) %>% 
    dplyr::mutate(
      sample = paste0("bs_", i)
    )
  bs_tib <- dplyr::bind_rows(bs_tib, bsample)
}

here::here("data-raw/dsr_ch07_boot_data.csv") %>%
  readr::write_csv(bs_tib, path = .)
```

```{r}

bs_tib <- here::here("data-raw/dsr_ch07_boot_data.csv") %>% 
  readr::read_csv()

bs_tib %>% 
  dplyr::filter(sample == "Data") %>% 
    dplyr::select(-sample)

bs_tib %>% 
  dplyr::filter(sample == "bs_1") %>% 
    dplyr::select(-sample)

bs_tib %>% 
  dplyr::filter(sample == "bs_2") %>% 
    dplyr::select(-sample)

bs_tib %>% 
  dplyr::filter(sample == "bs_3") %>% 
    dplyr::select(-sample)

bs_tib %>% 
  dplyr::filter(sample == "bs_4") %>% 
    dplyr::select(-sample)

bs_tib %>% 
  dplyr::filter(sample == "bs_5") %>% 
    dplyr::select(-sample)

```


